import { makeStyles } from "@material-ui/core";

export const formStyle = makeStyles({
  content: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    height: "60vh",
    alignItems: "center",
  },
  form: {
    marginTop: "20px",
    minWidth: "320px",
    margin: "12px auto",
    width: "50%",
    maxWidth: "800px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  labelSpanContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  label: {
    fontFamily: "-apple-system, sans-serif",
    fontSize: "16px",
    fontWeight: 600,
    color: "#880494",
    margin: "12px 4px",
  },
  span: {
    fontFamily: "-apple-system, sans-serif",
    fontSize: "14px",
    fontWeight: 400,
    color: "#454545",
  },
  input: {
    width: "75%",
    minWidth: "320px",
    height: "50px",
    fontFamily: "-apple-system, sans-serif",
    fontSize: "14px",
    fontWeight: 400,
    color: "#333333",
    padding: "4px 12px",
    paddingRight: "50px",
    outline: "none",
    borderRadius: "4px 0 0 4px",
    border: "1px ridge rgba(136, 4, 148, .4)",
    transition: "border .2s",
    "&:focus": {
      border: "1px solid rgba(136, 4, 148, .8)",
    },
    "&:disabled": {
      cursor: "not-allowed",
    },
  },

  inputsAndSelectContent: {
    display: "flex",
    width: "100%",
    alignItems: "center",
  },
  maxButton: {
    outline: "none",
    background: "#fff",
    color: "#880494",
    fontFamily: "-apple-system, sans-serif",
    fontSize: "16px",
    fontWeight: 600,
    width: "50px",
    marginRight: "1px",
    border: "none",
    height: "42px",
    marginLeft: "-51px",
    transition: "color .2s",
    "&:hover": {
      cursor: "pointer",
      color: "#d90d9c",
    },
    "&:disabled": {
      cursor: "not-allowed",
      background: "#fff",
      color: "#880494",
    },
  },
  submitButtonContent: {
    marginTop: "20px",
    display: "flex",
    flexDirection: "row-reverse",
  },
  submitButton: {
    fontFamily: "-apple-system, sans-serif",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 24px",
    fontSize: "16px",
    fontWeight: 500,
    color: "#dadada",
    maxWidth: "600px",
    minWidth: "200px",
    height: "46px",
    outline: "none",
    border: "none",
    borderRadius: "8px",
    background: "#ac10c4",
    transition: "color, background .2s",
    "&:hover": {
      cursor: "pointer",
      color: "#fff",
      background: "#880494",
    },
    "&:disabled": {
      cursor: "not-allowed",
      background: "#ac10c4",
      color: "#dadada",
    },
  },
  verticalLine: {
    height: "36px",
    width: "1px",
    borderLeft: "1px solid #fafafa",
    margin: "0 14px",
  },
});
